#!/bin/bash
set -e

MODEL=$1
VERSION=23.05.3
BUILDDIR=/tmp/openwrt-build
BASE_PACKAGES=" \
  dropbear \
  tcpdump-mini \
  "

case $MODEL in
"gl-mt300n-v2")
  PLATFORM=ramips
  TYPE=mt76x8
  TARGET_DEVICE=ramips-mt76x8
  PROFILE=glinet_gl-mt300n-v2
  EXTRA_PACKAGES="\
    uboot-envtools \
    opennds \
    watchcat \
  "
  REMOVED_PACKAGES="\
    -odhcpd \
    -odhcpd-ipv6only \
    "
;;

"gl-ar300m")
  PLATFORM=ath79
  TYPE=generic
  TARGET_DEVICE=ath79-generic
  PROFILE=glinet_gl-ar300m16
  EXTRA_PACKAGES="\
    uboot-envtools \
    kmod-usb2 \
    kmod-usb-core \
    kmod-usb-storage \
    luci \
    luci-ssl \
    iwinfo \
    wpad-wolfssl \
    "
  REMOVED_PACKAGES="\
    -odhcpd \
    -odhcpd-ipv6only \
    -wpad-basic-wolfssl \
    -wpad-basic-mbedtls \
    -wpad-mini \
    "
;;

"gl-mt3000")
  PLATFORM=mediatek
  TYPE=filogic
  TARGET_DEVICE=mediatek-filogic
  PROFILE=glinet_gl-mt3000
  EXTRA_PACKAGES="\
    kmod-usb2 \
    kmod-usb-core \
    kmod-usb-storage \
    luci \
    luci-ssl \
    iwinfo \
    wpad-wolfssl \
    "
  REMOVED_PACKAGES="\
    -odhcpd \
    -odhcpd-ipv6only \
    -wpad-basic-wolfssl \
    -wpad-basic-mbedtls \
    -wpad-mini \
    "
;;

"gl-mt6000")
  PLATFORM=mediatek
  TYPE=filogic
  TARGET_DEVICE=mediatek-filogic
  PROFILE=glinet_gl-mt6000
  EXTRA_PACKAGES="\
    kmod-usb2 \
    kmod-usb-core \
    kmod-usb-storage \
    luci \
    luci-ssl \
    iwinfo \
    wpad-wolfssl \
    "
  REMOVED_PACKAGES="\
    -odhcpd \
    -odhcpd-ipv6only \
    -wpad-basic-wolfssl \
    -wpad-basic-mbedtls \
    -wpad-mini \
    "
;;

"gl-e750")
  VERSION="snapshot"  # Override the version for E750
  PLATFORM=ramips
  TYPE=mt76x8
  TARGET_DEVICE=ramips-mt76x8
  PROFILE=glinet_gl-mudi
  EXTRA_PACKAGES="\
    kmod-usb2 \
    kmod-usb-core \
    kmod-usb-storage \
    uboot-envtools \
    "
  REMOVED_PACKAGES="\
    -odhcpd \
    -odhcpd-ipv6only \
    "
;;

*)
  echo "specify build target (gl-mt300n-v2, gl-ar300m, gl-mt3000, gl-mt6000, or gl-e750)"
  exit 1
;;
esac

if [ ! -d ${BUILDDIR} ] ; then
  mkdir ${BUILDDIR}
fi

# the need for $TYPE and $TARGET_DEVICE seems dumb but it helps get aroudn the problem of downloads        ↓↓↓↓↓↓↓
# http://downloads.openwrt.org/releases/18.06.1/targets/ath79/generic/openwrt-imagebuilder-18.06.1-ath79-generic.Linux-x86_64.tar.xz
#http://downloads.openwrt.org/releases/18.06.1/targets/ipq40xx/generic/openwrt-imagebuilder-18.06.1-ipq40xx.Linux-x86_64.tar.xz

if [ "$VERSION" = "snapshot" ]; then
  IMAGEBUILDER_NAME="openwrt-imagebuilder-${PLATFORM}-${TYPE}.Linux-x86_64"
  DOWNLOAD_URL="https://downloads.openwrt.org/snapshots/targets/${PLATFORM}/${TYPE}/${IMAGEBUILDER_NAME}.tar.zst"  # Note the .tar.zst extension
else
  IMAGEBUILDER_NAME="openwrt-imagebuilder-${VERSION}-${TARGET_DEVICE}.Linux-x86_64"
  DOWNLOAD_URL="https://downloads.openwrt.org/releases/${VERSION}/targets/${PLATFORM}/${TYPE}/${IMAGEBUILDER_NAME}.tar.xz"
fi

if [ ! -d ${BUILDDIR}/${IMAGEBUILDER_NAME} ] ; then
  if [ ! -f ${BUILDDIR}/${IMAGEBUILDER_NAME}.tar.xz ]; then
   (cd ${BUILDDIR} && curl -C - -O ${DOWNLOAD_URL})
  fi

  if [ "$VERSION" = "snapshot" ]; then
    tar --zstd -xf ${BUILDDIR}/${IMAGEBUILDER_NAME}.tar.zst -C ${BUILDDIR}/
  else
    tar xfJ ${BUILDDIR}/${IMAGEBUILDER_NAME}.tar.xz -C ${BUILDDIR}/
  fi

fi

COMBINED_PACKAGE_LIST="`echo ${REMOVED_PACKAGES}` `echo ${BASE_PACKAGES}` `echo ${EXTRA_PACKAGES}`"
echo "Combined package list ${COMBINED_PACKAGE_LIST}"

CORES=$(nproc)

echo "Building ${VERSION} using ${CORES} cores..."
( cd ${BUILDDIR}/${IMAGEBUILDER_NAME} && sudo make -j${CORES} image PROFILE="$PROFILE" PACKAGES="$COMBINED_PACKAGE_LIST" )

echo "scp -O ${BUILDDIR}/${IMAGEBUILDER_NAME}/bin/targets/${PLATFORM}/${TYPE}/openwrt-${TARGET_DEVICE}-${PROFILE}-squashfs-sysupgrade.bin root@<dest>:/tmp"
